---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: callme-deployment-v1
spec:
  selector:
    matchLabels:
      app: callme
      version: v1
  template:
    metadata:
      labels:
        app: callme
        version: v1
    spec:
      containers:
        - name: callme
          image: cloudowski/callme-service
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /etc/podinfo
              name: podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: callme-deployment-v2
spec:
  selector:
    matchLabels:
      app: callme
      version: v2
  template:
    metadata:
      labels:
        app: callme
        version: v2
    spec:
      containers:
        - name: callme
          image: cloudowski/callme-service
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /etc/podinfo
              name: podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
