apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: caller-service-gateway-route
spec:
  hosts:
    - "*"
  gateways:
    - microservices-gateway
  http:
    - match:
        - headers:
            X-Version:
              exact: v1
          uri:
            prefix: "/caller"
      rewrite:
        uri: " "
      route:
        - destination:
            host: caller-service.workshop.svc.cluster.local
            subset: v1
      retries:
        attempts: 3
        retryOn: 5xx
    - match:
        - uri:
            prefix: "/caller"
          headers:
            X-Version:
              exact: v2
      rewrite:
        uri: " "
      route:
        - destination:
            host: caller-service.workshop.svc.cluster.local
            subset: v2
      timeout: 1s
      retries:
        attempts: 3
        retryOn: 5xx
        perTryTimeout: 0.33s
    - match:
        - uri:
            prefix: "/caller"
      rewrite:
        uri: " "
      route:
        - destination:
            host: caller-service.workshop.svc.cluster.local
            subset: v1
          weight: 20
        - destination:
            host: caller-service.workshop.svc.cluster.local
            subset: v2
          weight: 80
